### ISSUE TITLE
Requriments Error 🤡 

### ISSUE THREAD

**Issue by INDxPIYUSH** [Lawxsz/make-u-own-stealer#10]
Bro at least provide a proper requirements file :/
what is Crypto.Cipher i installed it with pip still showing error 
please help

**Comment by Lawxsz** [comment]
yes sorry, this are only scripts not a Stealer Fully. Install pycryptodome

**Comment by INDxPIYUSH** [comment]
exactly which files am i supposed to use the one in scripts folder or setup folder ?
