### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ivegot0bitches** [Lawxsz/make-u-own-stealer#16]
Implement a virus total bypasses
Implement discord virus message bypasser
Implement windows defender bypasser
Implement discord emails and passwords
Implement an obfuscator (if you didnt)
Implement Webcam picture 
These are just suggestions btw xd
I'm studying for my finals so I couldn't really test your program
Will test soon though

**Comment by ivegot0bitches** [comment]
Just list of suggestions I think would make any stealer better :)

**Comment by Lawxsz** [comment]
tyyy :))
