### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by 0deep0** [Lawxsz/make-u-own-stealer#2]
it would be awsome if u can add uploading a file and run it, so it steals and take screenshots and pics and it uploads a file and run it. 
it would be so cool if u can do that.
thank u

**Comment by Lawxsz** [comment]
You mean take a screenshot of the computer, I'll do that.

**Comment by 0deep0** [comment]
no I mean run a whole diff program like a rat

**Comment by Lawxsz** [comment]
> no I mean run a whole diff program like a rat

maybe
