### ISSUE TITLE
bro this is ass

### ISSUE THREAD

**Issue by ParrotPatcher** [Lawxsz/make-u-own-stealer#9]
why are u making a stealer open src when theres alr stealers no duel hook giving open source and more options this is pretty much just a bunch of skided scripts

**Comment by Lawxsz** [comment]
I'm giving only scripts not a Stealer

**Comment by Lawxsz** [comment]
and are free not PAID scripts

**Comment by Lawxsz** [comment]
and are free not PAID scripts
